apiVersion: v1
kind: Service
metadata:
  name: bridge-service
spec:
  selector:
    app: challenge
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30000  # This will be overwritten by deploy_challenge function
  type: NodePort
