apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: instance-manager-clusterrole
rules:
- apiGroups: [""]
  resources: ["services", "pods"]
  verbs: ["get", "list", "create", "delete"]
