apiVersion: v1
kind: Secret
metadata:
  name: portforward-sa-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: portforward-sa
type: kubernetes.io/service-account-token
