apiVersion: apps/v1
kind: Deployment
metadata:
  name: instance-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: instance-manager
  template:
    metadata:
      labels:
        app: instance-manager
    spec:
      serviceAccountName: default  # Explicitly specifying the service account
      containers:
      - name: instance-manager
        image: gcr.io/edurangectf/instance-manager
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: instance-manager
  namespace: default
  annotations:
    cloud.google.com/l4-rbs: "enabled"
    cloud.google.com/load-balancer-type: "External"
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: LoadBalancer
  selector:
    app: instance-manager
  loadBalancerIP: 34.83.141.170
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
