version: '3.8'

networks:
  webos-network:
    driver: bridge

services:
  flask-backend:
    build: ./bridge
    container_name: flask-backend
    networks:
      - webos-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5000:5000"
    depends_on:
      - target-container

  target-container:
    build: ./debian
    container_name: target-container
    networks:
      - webos-network
    ports:
      - "2222:22"
