apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: metallb-system
  name: instance-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: instance-manager
  template:
    metadata:
      labels:
        app: instance-manager
    spec:
      containers:
      - name: instance-manager
        image: rydersel/instance-manager:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  namespace: metallb-system
  name: instance-manager
spec:
  selector:
    app: instance-manager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
