apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-1-challenge
  labels:
    category: web
    challenge: web-1
spec:
  replicas: 3
  selector:
    matchLabels:
      category: web
      challenge: web-1
  template:
    metadata:
      labels:
        category: web
        challenge: web-1
    spec:
      containers:
      - name: web-1
        image: gcr.io/edurangectf/web-1
        resources:
          limits:
            cpu: 100m
            memory: 150Mi
          requests:
            cpu: 10m
            memory: 30Mi
        ports:
        - containerPort: 9999
          name: port-9999
        env:
        - name: FLAG
          valueFrom:
            secretKeyRef:
              name: flag-secret
              key: flag
---
apiVersion: v1
kind: Service
metadata:
  name: web-1-challenge-service
  labels:
    category: web
    challenge: web-1
spec:
  type: NodePort
  selector:
    category: web
    challenge: web-1
  ports:
    - port: 9999
      targetPort: 9999
      nodePort: 30016
